FROM nginx:alpine

COPY ./frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# FROM node:latest
# WORKDIR /app
# COPY ./frontend/package.json ./
# RUN npm install
# COPY ./frontend .
# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]