FROM nginx:alpine

COPY ./dist /usr/share/nginx/html

RUN sed -i 's|location / {|location / {\n        try_files $uri $uri/ /index.html;|' /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
