FROM python:3.11-slim

RUN mkdir /fastapi_app

WORKDIR /fastapi_app

COPY ./backend/requirements.txt ./
COPY ./backend/scripts scripts/

RUN chmod a+x scripts/*.sh && \
    pip install -r requirements.txt gunicorn==21.2.0 fastapi-cache2==0.2.0 redis==4.4.2

COPY ./backend .

EXPOSE 8000
