"""rename_table

Revision ID: f8ab8b9b0314
Revises: aa1456794b50
Create Date: 2023-11-21 12:22:59.270466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8ab8b9b0314"
down_revision: Union[str, None] = "aa1456794b50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_administrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("position", sa.String(length=2000), nullable=True),
        sa.Column("photo", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("administrators")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrators",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "full_name", sa.VARCHAR(length=150), autoincrement=False, nullable=True
        ),
        sa.Column(
            "position", sa.VARCHAR(length=2000), autoincrement=False, nullable=True
        ),
        sa.Column("photo", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="administrators_pkey"),
    )
    op.drop_table("school_administrations")
    # ### end Alembic commands ###
