"""gallery_sub_pos_nullable

Revision ID: 97f646ab6f3d
Revises: 4d29171bec91
Create Date: 2023-11-23 19:00:17.554783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f646ab6f3d'
down_revision: Union[str, None] = '4d29171bec91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery', 'is_achivement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('is_achivement', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
