"""posters

Revision ID: 5ab31ba77e29
Revises: b77da8b6aa53
Create Date: 2023-11-21 13:35:08.191217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ab31ba77e29"
down_revision: Union[str, None] = "b77da8b6aa53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news", sa.Column("created_at", sa.Date(), nullable=True))
    op.add_column("posters", sa.Column("date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posters", "date")
    op.drop_column("news", "created_at")
    # ### end Alembic commands ###
