"""add unique

Revision ID: c4df2ade5fd4
Revises: 8478f2530afc
Create Date: 2023-12-31 17:31:54.142915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4df2ade5fd4"
down_revision: Union[str, None] = "8478f2530afc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sub_departments",
        "sub_department_name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=120),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "sub_departments", ["sub_department_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sub_departments", type_="unique")
    op.alter_column(
        "sub_departments",
        "sub_department_name",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
