"""fix length

Revision ID: 265f2be58494
Revises: 60ef1c11f350
Create Date: 2023-11-17 12:42:43.794230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "265f2be58494"
down_revision: Union[str, None] = "60ef1c11f350"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "phone",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "phone",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=15),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
