"""administrations

Revision ID: aa1456794b50
Revises: b77da8b6aa53
Create Date: 2023-11-21 12:05:35.856273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa1456794b50"
down_revision: Union[str, None] = "b77da8b6aa53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("position", sa.String(length=2000), nullable=True),
        sa.Column("photo", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("administrators")
    # ### end Alembic commands ###
