"""change contacts and documents

Revision ID: 5acc78c5d97d
Revises: c2be75aaa046
Create Date: 2024-01-16 20:25:08.767547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5acc78c5d97d"
down_revision: Union[str, None] = "c2be75aaa046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "official_info")
    op.drop_column("contacts", "statement_for_admission")
    op.add_column("documents", sa.Column("is_pinned", sa.Boolean(), nullable=True))
    op.alter_column(
        "sub_departments",
        "description",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=10000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sub_departments",
        "description",
        existing_type=sa.String(length=10000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.drop_column("documents", "is_pinned")
    op.add_column(
        "contacts",
        sa.Column(
            "statement_for_admission", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "contacts",
        sa.Column("official_info", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
