DOCS_EXISTS = "Document with name: `%s` already exists."
NO_DATA_FOUND = "Documents not found."
NO_DOC_FOUND = "Documents with id: '%s' not found."
SERVER_ERROR = "Server error."
SUCCESS_DELETE = "Document with id `%s` was successfully deleted."
DELETE_ERROR = "Cannot delete pinned record."
SUCCESS_CREATE = "Documents have been created successfully."
ALREADY_EXISTS = "Documents already exists."
