"""new department

Revision ID: 4cd1c281d770
Revises: a0f006470948
Create Date: 2023-11-22 23:55:01.273770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4cd1c281d770"
down_revision: Union[str, None] = "a0f006470948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "main_departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_name", sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sub_departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub_department_name", sa.String(length=300), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("main_department_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["main_department_id"],
            ["main_departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("gallery")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gallery",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("is_video", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("pinned_position", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("media", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="gallery_pkey"),
    )
    op.drop_table("sub_departments")
    op.drop_table("main_departments")
    # ### end Alembic commands ###
