from src.contacts.models import *
from src.auth.models import *
from src.news.models import *
from src.posters.models import *
from src.administrations.models import *
from src.gallery.models import *
from src.departments.models import *
from src.achievements.models import *
from src.slider_main.models import *
