NO_DATA_FOUND = "No data found."
NO_RECORD = "Record not found."
SERVER_ERROR = "Server error has occurred."
USER_ALREADY_EXISTS = "User already exists."
DEPARTMENTS_EXISTS = "Department with name: `%s` already exists."
SUCCESS_DELETE = "Record with id: `%s` was successfully deleted."