NO_DATA_FOUND = "No data found."
NO_RECORD = "Record not found."
SERVER_ERROR = "Server error has occurred."
SUCCESS_DELETE = "Record with id: `%s` was successfully deleted."
INVALID_PHONE = "Invalid phone number. Please ensure your phone number contains only digits and the symbols +()- , and follows the formats: +38(XXX)XXX-XX-XX"
INVALID_FILE = "Unsupported file type: %s. Supported types: %s"
INVALID_PHOTO = "Unsupported media type: %s. Supported types: %s"
OVERSIZE_FILE = "File size exceeds the maximum allowed size (3MB)"
