NO_DATA_FOUND = "Slides not found"
NO_RECORD = "Slide not found in db"
SERVER_ERROR = "Server error"
SUCCESS_DELETE = "Slide with id `%s` was successfully deleted."
SLIDE_EXISTS = "Slide with title:`%s` already exists"
MAXIMUM_SLIDE = "Maximum slide limit reached, cannot create more"
